### ISSUE TITLE
Problems after vagrant suspend

### ISSUE THREAD

**Issue by nobuttsalex** [paliarush/vagrant-magento#81]
When doing a vagrant suspend and vagrant up the machine does not return to the same state it was before the suspend. During the vagrant up process I get the errors below which result in a lot of the config files in /etc like the php/mysql/vagrant folders not being created. I am running OS X 10.11.6 but my colleague who is on Windows 10 is not experiencing the same problem so it may be only on Macs or something I have done wrong. I cloned the project in my home folder and my user has admin permissions so I cannot see it being to do with permissions.

```
==> magento2.vagrant22: cp: 
==> magento2.vagrant22: cannot create regular file ‘/etc/varnish/default.vcl’
==> magento2.vagrant22: : No such file or directory
==> magento2.vagrant22: sed: can't read /etc/php/7.0/cli/conf.d/20-xdebug.ini: No such file or directory
==> magento2.vagrant22: ERROR: 
==> magento2.vagrant22: Module php7.0 does not exist!
==> magento2.vagrant22: sed: can't read /etc/php/7.0/cli/conf.d/20-xdebug.ini: No such file or directory
==> magento2.vagrant22: /tmp/vagrant-shell: line 91: /etc/php/7.0/cli/conf.d/20-xdebug.ini: No such file or directory
==> magento2.vagrant22: /etc/init.d/apache2: 64: .: 
==> magento2.vagrant22: Can't open /etc/apache2/envvars
==> magento2.vagrant22: /etc/init.d/apache2: 76: .: 
==> magento2.vagrant22: Can't open /etc/apache2/envvars
==> magento2.vagrant22: ERROR: APACHE_PID_FILE needs to be defined in /etc/apache2/envvars
```

I appreciate this could be a vagrant issue but I use vagrant for other things and have never experienced problems when vagrant suspending and vagrant upping.

**Comment by nobuttsalex** [comment]
Looked more into the issue, vagrant provision (which happens at the start of vagrant up) is emptying the /etc/guest folder on the host machine which means the files cannot be mounted to the virtual machine and the symlinks break to the /etc folder.

_edit_ Solution: comment out lines 48 and 49 in configure_environment_recurring.sh as this is deleting all the config files during a vagrant provision/vagrant up. I am not sure why the code is doing this.

**Comment by aarcro** [comment]
I use `vagrant resume` after `vagrant suspend` And get different errors:

```
$ vagrant resume
==> magento2.vagrant204: Resuming suspended VM...
==> magento2.vagrant204: Booting VM...
==> magento2.vagrant204: Waiting for machine to boot. This may take a few minutes...
    magento2.vagrant204: SSH address: 127.0.0.1:3204
    magento2.vagrant204: SSH username: vagrant
    magento2.vagrant204: SSH auth method: private key
==> magento2.vagrant204: Machine booted and ready!
==> magento2.vagrant204: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> magento2.vagrant204: flag to force provisioning. Provisioners marked to run always will still run.
==> magento2.vagrant204: Running provisioner: fix_no_tty (shell)...
    magento2.vagrant204: Running: inline script
==> magento2.vagrant204: Running provisioner: upgrade_environment_recurring (shell)...
    magento2.vagrant204: Running: /var/folders/6p/09t024v92z1f3cmkb_c29wlh0000gn/T/vagrant-shell20160922-78971-810mx4.sh
==> magento2.vagrant204: + use_php7=1
==> magento2.vagrant204: + sudo rm -f /etc/apt/sources.list.d/ondrej-php-7_0-trusty.list
==> magento2.vagrant204: + [[ 1 -eq 1 ]]
==> magento2.vagrant204: + grep -q 7.0.5
==> magento2.vagrant204: + /usr/bin/php7.0 -v
==> magento2.vagrant204: ++ isServiceAvailable varnish
==> magento2.vagrant204: ++ grep -Fq varnish
==> magento2.vagrant204: ++ service --status-all
==> magento2.vagrant204:  [ ? ]  apport
==> magento2.vagrant204:  [ ? ]  console-setup
==> magento2.vagrant204:  [ ? ]  cryptdisks
==> magento2.vagrant204:  [ ? ]  cryptdisks-early
==> magento2.vagrant204:  [ ? ]  dns-clean
==> magento2.vagrant204:  [ ? ]  irqbalance
==> magento2.vagrant204:  [ ? ]  killprocs
==> magento2.vagrant204:  [ ? ]  kmod
==> magento2.vagrant204:  [ ? ]  mysql
==> magento2.vagrant204:  [ ? ]  networking
==> magento2.vagrant204:  [ ? ]  ondemand
==> magento2.vagrant204:  [ ? ]  open-vm-tools
==> magento2.vagrant204:  [ ? ]  pppd-dns
==> magento2.vagrant204:  [ ? ]  rc.local
==> magento2.vagrant204:  [ ? ]  screen-cleanup
==> magento2.vagrant204:  [ ? ]  sendsigs
==> magento2.vagrant204:  [ ? ]  umountfs
==> magento2.vagrant204:  [ ? ]  umountnfs.sh
==> magento2.vagrant204:  [ ? ]  umountroot
==> magento2.vagrant204:  [ ? ]  unlink-configs
==> magento2.vagrant204: ++ echo 1
==> magento2.vagrant204: + is_varnish_installed=1
==> magento2.vagrant204: + [[ 1 -eq 0 ]]
==> magento2.vagrant204: + service mysql restart
==> magento2.vagrant204: mysql stop/waiting
==> magento2.vagrant204: mysql start/running, process 8598
==> magento2.vagrant204: Running provisioner: configure_environment_recurring (shell)...
    magento2.vagrant204: Running: /var/folders/6p/09t024v92z1f3cmkb_c29wlh0000gn/T/vagrant-shell20160922-78971-yvvlb.sh
==> magento2.vagrant204: + grep -q /vagrant/etc/guest
==> magento2.vagrant204: + cat /etc/apparmor.d/local/usr.sbin.mysqld
==> magento2.vagrant204: + config_dir=/etc
==> magento2.vagrant204: + configs=(apache2 php mysql varnish rabbitmq)
==> magento2.vagrant204: + process_configs /etc apache2
==> magento2.vagrant204: + configs_path=/etc
==> magento2.vagrant204: + configs=apache2
==> magento2.vagrant204: + for config in '"${configs[@]}"'
==> magento2.vagrant204: + [[ ! -d /vagrant/etc/guest/apache2 ]]
==> magento2.vagrant204: + [[ ! -f /vagrant/etc/guest/apache2 ]]
==> magento2.vagrant204: + [[ -d /etc/apache2 ]]
==> magento2.vagrant204: + [[ -f /etc/apache2 ]]
==> magento2.vagrant204: + for config in '"${configs[@]}"'
==> magento2.vagrant204: + [[ ! -d /vagrant/etc/guest/php ]]
==> magento2.vagrant204: + [[ ! -f /vagrant/etc/guest/php ]]
==> magento2.vagrant204: + [[ -d /etc/php ]]
==> magento2.vagrant204: + [[ -f /etc/php ]]
==> magento2.vagrant204: + for config in '"${configs[@]}"'
==> magento2.vagrant204: + [[ ! -d /vagrant/etc/guest/mysql ]]
==> magento2.vagrant204: + [[ ! -f /vagrant/etc/guest/mysql ]]
==> magento2.vagrant204: + [[ -d /etc/mysql ]]
==> magento2.vagrant204: + [[ -f /etc/mysql ]]
==> magento2.vagrant204: + for config in '"${configs[@]}"'
==> magento2.vagrant204: + [[ ! -d /vagrant/etc/guest/varnish ]]
==> magento2.vagrant204: + [[ ! -f /vagrant/etc/guest/varnish ]]
==> magento2.vagrant204: + [[ -d /etc/varnish ]]
==> magento2.vagrant204: + [[ -f /etc/varnish ]]
==> magento2.vagrant204: + for config in '"${configs[@]}"'
==> magento2.vagrant204: + [[ ! -d /vagrant/etc/guest/rabbitmq ]]
==> magento2.vagrant204: + [[ ! -f /vagrant/etc/guest/rabbitmq ]]
==> magento2.vagrant204: + [[ -d /etc/rabbitmq ]]
==> magento2.vagrant204: + [[ -f /etc/rabbitmq ]]
==> magento2.vagrant204: cp: 
==> magento2.vagrant204: cannot create regular file ‘/etc/varnish/default.vcl’
==> magento2.vagrant204: : No such file or directory
==> magento2.vagrant204: sed: can't read /etc/php/7.0/cli/conf.d/20-xdebug.ini: No such file or directory
==> magento2.vagrant204: ERROR: 
==> magento2.vagrant204: Module php7.0 does not exist!
==> magento2.vagrant204: sed: can't read /etc/php/7.0/cli/conf.d/20-xdebug.ini: No such file or directory
==> magento2.vagrant204: /tmp/vagrant-shell: line 91: /etc/php/7.0/cli/conf.d/20-xdebug.ini: No such file or directory
==> magento2.vagrant204: /etc/init.d/apache2: 64: .: 
==> magento2.vagrant204: Can't open /etc/apache2/envvars
==> magento2.vagrant204: /etc/init.d/apache2: 76: .: 
==> magento2.vagrant204: Can't open /etc/apache2/envvars
==> magento2.vagrant204: ERROR: APACHE_PID_FILE needs to be defined in /etc/apache2/envvars
==> magento2.vagrant204:  [ ? ]  apport
==> magento2.vagrant204:  [ ? ]  console-setup
==> magento2.vagrant204:  [ ? ]  cryptdisks
==> magento2.vagrant204:  [ ? ]  cryptdisks-early
==> magento2.vagrant204:  [ ? ]  dns-clean
==> magento2.vagrant204: cat: 
==> magento2.vagrant204: /etc/php/7.0/cli/php.ini
==> magento2.vagrant204: : No such file or directory
==> magento2.vagrant204: Running provisioner: export_env_variables_recurring (shell)...
    magento2.vagrant204: Running: /var/folders/6p/09t024v92z1f3cmkb_c29wlh0000gn/T/vagrant-shell20160922-78971-1kos8kj.sh
```

I was guessing the error was NFS related, but this time my mounts seem OK. My site still loads, but trying to run `m-bin-magento` gives more errors:

```
$ ./m-bin-magento list
+ arguments=list
+ cd /Users/aaron/src/JBS/vagrant-magento
+ vagrant ssh -c '$MAGENTO_ROOT/bin/magento list'

Fatal error: Uncaught Error: Call to undefined function Composer\Json\json_decode() in /Users/aaron/src/JBS/vagrant-magento/magento2ce/vendor/composer/composer/src/Composer/Json/JsonFile.php:152
Stack trace:
#0 /Users/aaron/src/JBS/vagrant-magento/magento2ce/vendor/composer/composer/src/Composer/Factory.php(269): Composer\Json\JsonFile->validateSchema(1)
#1 /Users/aaron/src/JBS/vagrant-magento/magento2ce/vendor/composer/composer/src/Composer/Factory.php(532): Composer\Factory->createComposer(Object(Composer\IO\BufferIO), '/Users/aaron/sr...', false)
#2 /Users/aaron/src/JBS/vagrant-magento/magento2ce/lib/internal/Magento/Framework/Composer/ComposerFactory.php(47): Composer\Factory::create(Object(Composer\IO\BufferIO), '/Users/aaron/sr...')
#3 /Users/aaron/src/JBS/vagrant-magento/magento2ce/lib/internal/Magento/Framework/Composer/ComposerInformation.php(362): Magento\Framework\Composer\ComposerFactory->create()
#4 /Users/aaron/src/JBS/vagrant-magento/magento2ce/lib/internal/Magento/Framework/Composer/ComposerInformation.php in /Users/aaron/src/JBS/vagrant-magento/magento2ce/vendor/composer/composer/src/Composer/Json/JsonFile.php on line 152
Connection to 127.0.0.1 closed.
```

**Comment by paliarush** [comment]
@nobuttsalex thank you for reporting this issue.

Directories are cleaned up to make [Accessing configs from IDE](https://github.com/paliarush/magento2-vagrant-for-developers#accessing-php-and-other-config-files) feature work. To be honest, I never do suspend that's why haven't seen this issue before. Instead I use `vagrant halt`. Also everything should work fine after hard VM reset.

I will look into this issue and fix it if quick fix is available, looks like low priority.
